# Generated by Django 5.2.6 on 2025-09-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='bus',
            new_name='bus_name',
        ),
        migrations.AddField(
            model_name='bus',
            name='no_of_seats',
            field=models.PositiveBigIntegerField(default=20),
            preserve_default=False,
        ),
    ]
