# Generated by Django 5.2.6 on 2025-09-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='react_time',
            new_name='reach_time',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='bus_name',
        ),
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.bus'),
        ),
    ]
