# Generated by Django 5.2.6 on 2025-09-18 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_bus_number_bus_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bookings.bus'),
        ),
    ]
